# Pipeline for install storing Password of NPA account sa-aad-networkselfservice@abnamro.onmicrosoft.com in KeyVault

#Following are Jobs designed within this pipeline
#
# Job 1: Store NPA Password in KeyVault
#

# Build Name
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)


# Variables - Global level
variables:
  npaaccountname: 'sa-aad-networkselfservice'
  keyVaultName: 'nss01-d-kv'
  resourcegroupname: 'nssd01-e-rg'
  serviceconnection_name: 'devops-azure-engineering'

  ## variabled for bug creation task
  system_definitionname: $(System.DefinitionName)
  OrganizationName: 'cbsp-abnamro'
  ProjectName: 'Azure'
  TeamName: 'Platform Enablement Team 1'
  ItemTypeName: 'Backlog items'
  ItemWorkType: 'Bug'
  ### artifacts path within self repo
  pwsh_script_path: $(System.DefaultWorkingDirectory)/Products/SelfServiceNetworkSolution/v1/Scripts
  ### Path to the bug creation template
  template_path: ../../../Pipelines/Templates/bug-creation-template.yaml

trigger: none

stages:
  - stage: After_Checkin
    displayName: After Checkin
    pool:
      vmImage: windows-latest
    jobs:
    - job: store_npa_password_in_kv
      condition: always()
      steps:
        - checkout: self
        - task: abnamrocbspazure.AbnAmro-CbspAzure-Products.AbnAmro-CbspAzure-Keyvault.AbnAmro-CbspAzure-KeyVault@1
          displayName: 'Key Vault'
          inputs:
            azureSubscription: $(serviceconnection_name)
            keyVaultName: $(keyVaultName)            
            action: setSecret
            resourceGroupName: $(resourcegroupname)
            secretName: $(npaaccountname)
            secretValue: $(secretValue)
        - template:  ${{variables['template_path']}}
          parameters:
            TeamName: 'Platform Enablement Team 1'
            ScriptPath: ${{variables['pwsh_script_path']}}