parameters:
- name: ServiceConnectionName
  type: string
- name: ApplicationInsightsName
  type: string

jobs:
  - job: create_appinsights
    displayName: Create CBSP Application Insights
    steps:
    - task: abnamrocbspazure.AbnAmro-CbspAzure-Products.AbnAmro-CbspAzure-AppInsights.AbnAmro-CbspAzure-AppInsights@1
      displayName: 'New: Network SelfService AppInsights'
      inputs:
        azureSubscription: ${{ parameters.ServiceConnectionName }}
        resourceGroupName: $(resourcegroup_name)
        applicationInsightsName: ${{ parameters.ApplicationInsightsName }}
        applicationType: other
        kind: api