parameters:
- name: ServiceConnectionName
  type: string
- name: StorageAccountName
  type: string

jobs:
  - job: create_storageaccount
    displayName: Create CBSP Storage Account
    steps:
    - task: abnamrocbspazure.AbnAmro-CbspAzure-Products.AbnAmro-CbspAzure-Storage.AbnAmro-CbspAzure-Storage@3
      displayName: 'New: Network SelfService Diagnostics StorageAccount'
      inputs:
        azureSubscription: ${{ parameters.ServiceConnectionName }}
        resourceGroupName: $(resourcegroup_name)
        storageAccountName: ${{ parameters.StorageAccountName }}
        defaultAclAction: Allow
        addStandardIPRanges: false
        allowTrustedAzureServices: true
        enableAdvancedThreatProtection: true