# Build to update the Service Connections used in the cbsp-selfservice-platform-validation organization.

# Build Name
name: PlatformValidationSCKeyRotation-$(Date:yyyyMMdd)-$(SourceBranchName)-$(Rev:rr)

# Trigger
trigger: none

# Schedule
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight NPA Password Rotation
  always: true
  branches:
    include:
    - master  

# Global Variables
variables:
  ServiceConnectionSuffix: 'vdc2s'
  subscriptionId: '37523455-06d3-4fb9-8306-61a3c08f4d09'
  Environment: 'Production'
  ResourceGroupName: 'platformvalidation-e-rg'

  ## variables for bug creation task
  system_definitionname: $(System.DefinitionName)
  OrganizationName: 'cbsp-abnamro'
  ProjectName: 'Azure'
  ItemTypeName: 'Backlog items'
  ItemWorkType: 'Bug'
  ### artifacts path within self repo
  pwsh_script_path: $(System.DefaultWorkingDirectory)/Products/SelfServiceNetworkSolution/v1/Scripts
  ### Path to the bug creation template
  template_path: Templates/bug-creation-template.yaml

pool:
  vmImage: windows-latest

stages: 
  # Stage to package the extension
  - stage: KeyRotation_ServiceConnection
    jobs:
    - job: retrieve_pattoken
      displayName: KeyRotation Validation Service Connections
      condition: always()
      steps:
      - checkout: self
      - task: abnamrocbspazure.AbnAmro-CbspAzure-Products.AbnAmro-CbspAzure-Keyvault.AbnAmro-CbspAzure-KeyVault@1
        displayName: 'Key Vault'
        name: get_pattoken
        inputs:
          azureSubscription: 'devops-azure-engineering'
          keyVaultName: 'nss01-d-kv'
          action: getSecret
          resourceGroupName: 'nssd01-e-rg'
          secretName: 'npa-pat-createupdateseviceconnections'
      - template:  ${{variables['template_path']}}
        parameters:
          TeamName: 'Platform Enablement Team 1'
          ScriptPath: ${{variables['pwsh_script_path']}}

    - job: keyrotation_validation_serviceconnection
      displayName: KeyRotation devops-azure-platform-validation-p-vdc2s Service Connections
      dependsOn: retrieve_pattoken
      condition: eq(dependencies.retrieve_pattoken.result, 'Succeeded')
      variables:
        pattoken: $[ dependencies.retrieve_pattoken.outputs['get_pattoken.SecretValue'] ]
        ServiceLongName: 'azure-platform-validation'
        servicePrincipalName: 'devops-azure-platform-validation-p-vdc2s'
        ServiceShortName: 'azure-platform-validation'
      steps:
      - checkout: self
      - task: abnamrocbspazure.AbnAmro-CbspAzure-Products.AbnAmro-CbspAzure-ServicePrincipal.AbnAmro-CbspAzure-Azure-Service-Principal@3
        displayName: 'Create/update Service Connection with Service Principal'
        inputs:
          azureSubscription: 'devops-selfservice-azuread'
          Action: createServiceConnection
          ServiceConnectionNameSuffix: '$(ServiceConnectionSuffix)'
          SpecifyAzureDevOpsOrganization: true
          AzureDevOpsOrganization: 'cbsp-selfservice-platform-validation'
          AzureDevOpsProjectName: PlatformProductValidation
          AzureDevOpsPAT: '$(pattoken)'
          SpecifySubscription: true
          SubscriptionId: '$(subscriptionId)'
          ScopeToResourceGroup: false
      - template:  ${{variables['template_path']}}
        parameters:
          TeamName: 'Platform Enablement Team 1'
          ScriptPath: ${{variables['pwsh_script_path']}}

    - job: keyrotation_selfservice_validation_serviceconnection
      displayName: KeyRotation devops-selfservice01-platform-validation-p-vdc2s Service Connections
      dependsOn: retrieve_pattoken
      condition: eq(dependencies.retrieve_pattoken.result, 'Succeeded')
      variables:
        pattoken: $[ dependencies.retrieve_pattoken.outputs['get_pattoken.SecretValue'] ]
        ServiceLongName: 'selfservice01-platform-validation'
        servicePrincipalName: 'devops-selfservice01-platform-validation-p-vdc2s'
        ServiceShortName: 'selfservice01-platform-validation'
      steps:
      - checkout: self
      - task: abnamrocbspazure.AbnAmro-CbspAzure-Products.AbnAmro-CbspAzure-ServicePrincipal.AbnAmro-CbspAzure-Azure-Service-Principal@3
        displayName: 'Create/update Service Connection with Service Principal'
        inputs:
          azureSubscription: 'devops-selfservice-azuread'
          Action: createServiceConnection
          ServiceConnectionNameSuffix: '$(ServiceConnectionSuffix)'
          SpecifyAzureDevOpsOrganization: true
          AzureDevOpsOrganization: 'cbsp-selfservice-platform-validation'
          AzureDevOpsProjectName: PlatformProductValidation
          AzureDevOpsPAT: '$(pattoken)'
          SpecifySubscription: true
          SubscriptionId: '$(subscriptionId)'
          ScopeToResourceGroup: false
      - template:  ${{variables['template_path']}}
        parameters:
          TeamName: 'Platform Enablement Team 1'
          ScriptPath: ${{variables['pwsh_script_path']}}
