# Pipeline for rotating the NPA password daily.
# More info can be found here: https://dev.azure.com/cbsp-abnamro/Azure/_wiki/wikis/Azure.wiki/779/Process-automated-changing-cloud-NPA-password

# Script NPA-Rotate-Password needs the following permissions:
#    - The account under which the script is executed required Get Secret permissions
#    - The account of which the password is changed required Set Secret permissions

#Following are Jobs designed within this pipeline
#
# Job 1: Rotate NPA password
#

# Build Name
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranch)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- none

# Schedule
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight NPA Password Rotation
  always: true
  branches:
    include:
    - master  

# Global variables
variables:
  serviceconnection_name: 'devops-azure-engineering'
  ## artifacts path within self repo
  npa_rotation_path: $(System.DefaultWorkingDirectory)/RecurringTasks/Daily
  TeamName: 'Platform Enablement Team 1'

  ## variables for bug creation task
  system_definitionname: $(System.DefinitionName)
  OrganizationName: 'cbsp-abnamro'
  ProjectName: 'Azure'
  ItemTypeName: 'Backlog items'
  ItemWorkType: 'Bug'
  ### artifacts path within self repo
  pwsh_script_path: $(System.DefaultWorkingDirectory)/Products/SelfServiceNetworkSolution/v1/Scripts
  ### Path to the bug creation template
  template_path: Templates/bug-creation-template.yaml

stages:
  - stage: rotate_npa_password
    displayName: Rotate NPA password
    pool:
      vmImage: windows-latest
    jobs:
    - job: rotate_npa_password
      displayName: Rotate NPA password
      condition: always()
      variables:
        keyvaultName: 'nss01-d-kv'
        UsernameSecretName: 'sa-aad-networkselfservice-account'
        PasswordSecretName: 'sa-aad-networkselfservice'
        tenantId: '3a15904d-3fd9-4256-a753-beb05cdf0c6d'
      steps:
      - checkout: self
        persistCredentials: true
      - task: AzurePowerShell@4
        displayName: 'az ps: Rotate NPA Password'
        enabled: true
        inputs:
          azureSubscription: $(serviceconnection_name)
          pwsh: false
          scriptType: 'filepath'
          scriptPath: $(npa_rotation_path)/NPA-Rotate-Password.ps1
          scriptArguments: "-KeyVaultName $(keyvaultName) -UsernameSecretName $(UserNameSecretName) -PasswordSecretName $(PasswordSecretName) -TenantId $(tenantId)"
          azurePowerShellVersion: 'latestVersion'
      - template:  ${{variables['template_path']}}
        parameters:
          TeamName: 'Platform Enablement Team 1'
          ScriptPath: ${{variables['pwsh_script_path']}}
